### ISSUE TITLE
Version 2, "Directories & files fuzz - In progress" Never stop

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Directories & files fuzz" scan never end

### Expected Behavior

"Directories & files fuzz"

### Steps To Reproduce

Start any scan

### Environment

```markdown
- reNgine: 2
- OS: Kali
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by psyray** [comment]
I've the same problem.
Could you try to set the threads to 100 and test again ?
It works for me.

**Comment by zinwelzl** [comment]
You mean like this?

My VM is 4 CPU and 8 GB RAM.
What config should I change in env and yaml files (and any other files)?

dir_file_fuzz: {
  'auto_calibration': true,
  'enable_http_crawl': true,
  'rate_limit': 150,
  'extensions': ['html', 'php','git','yaml','conf','cnf','config','gz','env','log','db','mysql','bak','asp','aspx','txt','conf','sql','json','yml','pdf'],
  'follow_redirect': false,
  'max_time': 0,
  'match_http_status': [200, 204],
  'recursive_level': 2,
  'stop_on_error': false,
  'timeout': 5,
  'threads': 100,
  'wordlist_name': 'dicc'

**Comment by zinwelzl** [comment]
Nothing change with threads 100.

In terminal "Background saving terminated with success", in GUI dir "running", and no data in GUI "Directories".
Every other tab have data, only "Directories" don't have anything.

**Comment by zinwelzl** [comment]
Even when I create new yaml file for engine, and for dir search put only "html", dir scan never end.

Directories & files fuzzIn - progress
Logs
ffuf -w /usr/src/wordlist/dicc.txt -e html -p 0.015 -recursion -recursion-depth 2 -t 100 -timeout 5 -ac -mc 200,204 -u https://__MY_SITE__/FUZZ -json

Every other scan, save output in "/usr/src/scan_results/", except dir fuzz.

nuclei -j -irr -l /usr/src/scan_results/__MY_SITE___19/urls_unfurled.txt -c 50 -retries 1 -rl 150 -timeout 5 -silent -t /root/nuclei-templates -severity info
netlas search -d domain -i domain domain:"*.__MY_SITE__" -f json | grep -oE '([a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?\.)+__MY_SITE__' > /usr/src/scan_results/psvt.ovh_19/subdomains_netlas.txt
etc.

**Comment by psyray** [comment]
FFUF did not finish also for me, but it records data to the db
I've tested with a small wordlist without extensions to be sure to have results and test the db save
Here's is the scanEngine conf
```
dir_file_fuzz: {
  'auto_calibration': true,
  'enable_http_crawl': true,
  'rate_limit': 150,
  'extensions': [],
  'follow_redirect': false,
  'max_time': 0,
  'match_http_status': [200,204,301,302,307,401,403,405,500],
  'recursive_level': 2,
  'stop_on_error': false,
  'timeout': 5,
  'threads': 100,
  'wordlist_name': 'fuzz_boom'
}
```

FFUF stop scanning for an unknown reason at ~ 1/4 of the progress (here is the logs from the **Scan Timeline** on the scan history Dashboard that stopped at **admin/user_count** ~ 1000/4842)
![image](https://github.com/yogeshojha/rengine/assets/1230954/56ea8f59-959d-4498-bcb3-bb275a55d29a)

Task never finish, I need to stop it into subscan history to remove ffuf process

I've took the command line from the logs popup and launched in celery container
`ffuf -w /usr/src/wordlist/fuzz_boom.txt -p 0.015 -recursion -recursion-depth 2  -t 100 -timeout 5 -ac -mc 200,204,301,302,307,401,403,405,500 -u https://ginandjuice.shop/FUZZ -json`

Scan finish in 3sec
![image](https://github.com/yogeshojha/rengine/assets/1230954/13998049-3678-4899-83b0-eb4eaa182e31)

So db save is working, but FFUF never finish

**Comment by psyray** [comment]
> Every other scan, save output in "/usr/src/scan_results/", except dir fuzz.
> 
> nuclei -j -irr -l /usr/src/scan_results/__MY_SITE___19/urls_unfurled.txt -c 50 -retries 1 -rl 150 -timeout 5 -silent -t /root/nuclei-templates -severity info netlas search -d domain -i domain domain:"*.**MY_SITE**" -f json | grep -oE '([a-zA-Z0-9](%5B-a-zA-Z0-9%5D*%5Ba-zA-Z0-9%5D)?.)+**MY_SITE**' > /usr/src/scan_results/psvt.ovh_19/subdomains_netlas.txt etc.

Nuclei does not save in scan_results.
The reason behind that is to have results in the UI when it ouputs, not when the scan finish.
Only for tool with JSON output, like FFUF and Nuclei

https://github.com/yogeshojha/rengine/pull/742
![image](https://github.com/yogeshojha/rengine/assets/1230954/2483c65b-fd7a-4237-b1a6-98ad1b5729ce)

**Comment by zinwelzl** [comment]
Is there solution for FFUF to finish?

**Comment by psyray** [comment]
> Is there solution for FFUF to finish?

Not at this time, nobody seems to investigate on it.
I don't have the time to do this at the moment.
Maybe next week

**Comment by zinwelzl** [comment]
Thanks.

**Comment by carboncrystal** [comment]
Is there any chance someone can fix this bug? Fuzz simply doesn't work in v 2.0.1, it never finishes and never displays any results.

**Comment by ocervell** [comment]
We can also exclude problems in `reNgine/tasks.py`:`stream_command` function I believe, as this works normally:

`docker-compose exec rengine /bin/bash`
`python3`

```py
from reNgine.tasks import stream_command
results = stream_command("ffuf -w /usr/src/app/test.txt -e html,php,git,yaml,conf,cnf,config,gz,env,log,db,mysql,bak,asp,aspx,
txt,conf,sql,json,yml,pdf -p 0.05 -recursion -recursion-depth 2  -t 30 -timeout 5 -ac -mc 200,204 -u http://testphp.vulnweb.co
m/FUZZ -json")
for result in results: 
  print(result)
```

Weirdly only `ffuf` behaves this way, other tasks run normally.

I would +1 for a Celery issue but I'm not sure what to look for exactly ... There was some changes on Celery queues / workers scaling that I'm unaware of.

**Comment by ocervell** [comment]
Might be linked with ANSI decoding as ffuf outputs ANSI codes.

**Comment by psyray** [comment]
> Might be linked with ANSI decoding as ffuf outputs ANSI codes. I'll send a PR fix shortly, but please test it as my bandwith is low right now.

If you push the PR i'll test it, no problem :+1:

**Comment by psyray** [comment]
Fixed #1063

**Comment by juanschallibaum** [comment]
Hello, I've been experiencing the same issue with directory scanning as discussed in the ongoing GitHub issue. Last week, I updated rengine to version 2.0.2 and made sure to incorporate the latest code changes from the recent commits that closed the issue. However, the problem persists: the directory scan never completes. Even after creating a new scan post-update, the situation hasn't improved. If you need any additional information about the versions I'm using or any other details, please feel free to ask. I'm testing this from Ubuntu 22.04. Thank you!

**Comment by AnonymousWP** [comment]
> Hello, I've been experiencing the same issue with directory scanning as discussed in the ongoing GitHub issue. Last week, I updated rengine to version 2.0.2 and made sure to incorporate the latest code changes from the recent commits that closed the issue. However, the problem persists: the directory scan never completes. Even after creating a new scan post-update, the situation hasn't improved. If you need any additional information about the versions I'm using or any other details, please feel free to ask. I'm testing this from Ubuntu 22.04. Thank you!

Try updating all tools, especially httpx that's used for fuzzing.

**Comment by psyray** [comment]
> Hello, I've been experiencing the same issue with directory scanning as discussed in the ongoing GitHub issue. Last week, I updated rengine to version 2.0.2 and made sure to incorporate the latest code changes from the recent commits that closed the issue. However, the problem persists: the directory scan never completes. Even after creating a new scan post-update, the situation hasn't improved. If you need any additional information about the versions I'm using or any other details, please feel free to ask. I'm testing this from Ubuntu 22.04. Thank you!

Have you do a `make down` and `make up` ?
Try this and upgrade all tools
Directory fuzzing is working now, I'll use it everyday.
If it does not stop monitor server usage (RAM, I/O...)
If it persists open an issue with logs
