### ISSUE TITLE
Error While Installing

### ISSUE THREAD

**Issue by omemishra** [yogeshojha/rengine#353]
Bro please tell me the solution of this 

The command '/bin/sh -c GO111MODULE=auto go get -u -v github.com/projectdiscovery/httpx/cmd/httpx' returned a non-zero code: 1
ERROR: Service 'web' failed to build
make: *** [Makefile:25: build] Error 1

i am getting this error while installing

regards
Ome

**Comment by payloadartist** [comment]
Try my fix - #346 

It will work hopefully. I added the missing dependency.

Cheers

**Comment by foozzi** [comment]
> Try my fix - #346
> 
> It will work hopefully. I added the missing dependency.
> 
> Direct link to my patch - https://github.com/payloadartist/rengine/tree/patch-1
> 
> Cheers

ubuntu 20, with your patch(

```
# github.com/projectdiscovery/naabu/v2/pkg/scan
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/connect.go:18:3: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:244:4: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:416:5: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:430:6: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:435:6: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:478:4: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:484:5: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:516:4: undefined: gologger.Warningf
root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan_unix.go:140:9: undefined: gologger.Debugf
The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder     github.com/projectdiscovery/nuclei/v2/cmd/nuclei     github.com/lc/gau     github.com/projectdiscovery/naabu/v2/cmd/naabu' returned a non-zero code: 2
ERROR: Service 'web' failed to build
make: *** [Makefile:25: build] Error 1
```

**Comment by ciarancotter** [comment]
I am having the same problem.

**Comment by foozzi** [comment]
naabu use old syntax for **gologger** 
https://github.com/projectdiscovery/naabu/commit/17be83c51a638290ec81a05518473647a7994551

**Comment by omemishra** [comment]
Thank you bhai log......

**Comment by omemishra** [comment]
> > Try my fix - #346
> > It will work hopefully. I added the missing dependency.
> > Direct link to my patch - https://github.com/payloadartist/rengine/tree/patch-1
> > Cheers
> 
> ubuntu 20, with your patch(
> 
> ```
> # github.com/projectdiscovery/naabu/v2/pkg/scan
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/connect.go:18:3: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:244:4: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:416:5: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:430:6: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:435:6: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:478:4: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:484:5: undefined: gologger.Debugf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan.go:516:4: undefined: gologger.Warningf
> root/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.3/pkg/scan/scan_unix.go:140:9: undefined: gologger.Debugf
> The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder     github.com/projectdiscovery/nuclei/v2/cmd/nuclei     github.com/lc/gau     github.com/projectdiscovery/naabu/v2/cmd/naabu' returned a non-zero code: 2
> ERROR: Service 'web' failed to build
> make: *** [Makefile:25: build] Error 1
> ```

service docker start


it will start docker

then use it

**Comment by omemishra** [comment]
> Try my fix - #346
> 
> It will work hopefully. I added the missing dependency.
> 
> Direct link to my patch - https://github.com/payloadartist/rengine/tree/patch-1
> 
> Cheers

getting this error with your build.

github.com/lc/gau/providers
github.com/lc/gau
The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder     github.com/projectdiscovery/nuclei/v2/cmd/nuclei     github.com/lc/gau     github.com/projectdiscovery/naabu/cmd/naabu' returned a non-zero code: 2
ERROR: Service 'web' failed to build
make: *** [Makefile:25: build] Error 1

**Comment by payloadartist** [comment]
I updated it, added the ```go get``` commands in separate lines. Try again and lmk. It works fine me for me though!

Cheers

**Comment by payloadartist** [comment]
> I updated the patch, added the `go get` commands in separate lines. Try again and lmk. It works fine me for me though strangely!
> 
> Cheers

This worked. You can check, the build succeeded after putting them in separate lines -> https://github.com/yogeshojha/rengine/pull/346/checks?check_run_id=1971249086

Cheers

**Comment by omemishra** [comment]
i have downloaded now only but have you pushed the patch now bro?

**Comment by payloadartist** [comment]
> i have downloaded now only but have you pushed the patch now bro?

yes I changed it *just now* to fix it. so if you have the older version, you can do ```git pull``` to update that from my patch branch

Cheers

**Comment by omemishra** [comment]
getting this error

`github.com/lc/gau
github.com/projectdiscovery/nuclei/v2/pkg/matchers
github.com/projectdiscovery/nuclei/v2/pkg/requests
github.com/projectdiscovery/subfinder/v2/cmd/subfinder
github.com/projectdiscovery/naabu/pkg/scan
hash github.com/projectdiscovery/naabu/pkg/scan
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/connect.go:18:3: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:52:3: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:59:3: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:63:3: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:70:3: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:105:4: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:152:6: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:166:7: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:171:7: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:193:6: undefined: gologger.Debugf
root/go/pkg/mod/github.com/projectdiscovery/naabu@v1.1.4/pkg/scan/scan.go:193:6: too many errors
github.com/projectdiscovery/nuclei/v2/pkg/templates
The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder     github.com/projectdiscovery/nuclei/v2/cmd/nuclei     github.com/lc/gau     github.com/projectdiscovery/naabu/cmd/naabu' returned a non-zero code: 2
ERROR: Service 'web' failed to build
make: *** [Makefile:25: build] Error 1
`

**Comment by payloadartist** [comment]
can you git pull and check again?

I think you are still on older version of patch

Cheers

**Comment by omemishra** [comment]
bro i have done this but i am getting same error .

is this because of go version because mine is latest.


/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder     github.com/projectdiscovery/nuclei/v2/cmd/nuclei     github.com/lc/gau     github.com/projectdiscovery/naabu/cmd/naabu

**Comment by yogeshojha** [comment]
Looks like this will take some time. The PR from @payloadartist #346 suggests to use Naabu v2, while the build is successful from his PR, but naabu v2 has changed few commands and we may need to make necessary changes in Scan Engine. Basically tasks.py.

Please stay tuned.

**Comment by omemishra** [comment]
yes because of that i was getting error.

waiting for that bro ..... 

Kam se kam installation to ho jaaye.

**Comment by yogeshojha** [comment]
But if you skip Port scan, it should be working right? I just did the full scan, only the port scan failed, apart from that looks good on my end.

**Comment by omemishra** [comment]
bro i am not able to install it ....


make build getting failed every time i try to install the latest version.

Please check

**Comment by yogeshojha** [comment]
Yes, I mean the patch sent by @payloadartist is a valid PR except that port scan is not working. 

Can you clone this and give it a try https://github.com/payloadartist/rengine

**Comment by payloadartist** [comment]
> Can you clone this and give it a try https://github.com/payloadartist/rengine

Just to clarify the ```patch-1``` branch has successful build, my master branch doesn't have the fix.

so use, ```git pull origin patch-1``` to clone that branch.

Cheers

**Comment by yogeshojha** [comment]
I don't think if @omemishra would be able to download patch as such. Only me and you can download the patch, even more precisely using `gh` this can be downloaded 

`gh pr checkout 346`

@omemishra see if you can download his PR patch `gh pr checkout 346`

**Comment by foozzi** [comment]
> bro i am not able to install it ....
> 
> make build getting failed every time i try to install the latest version.
> 
> Please check

same problem...

**Comment by foozzi** [comment]
i'm install naabu@dev and now all working fine.

tomorrow I will post a bash script for a normal installation (with the creation of a regular user for security)

**Comment by foozzi** [comment]
```
git clone https://github.com/yogeshojha/rengine.git -b patch-1
```
work fine.

**Comment by omemishra** [comment]
yo bro fine now ...

manually install the dev of naabu

**Comment by foozzi** [comment]
> yo bro fine now ...
> 
> manually install the dev of naabu

but the problem was obvious in naabu, manually everything was installed fine, but the patch worked 100%

**Comment by yogeshojha** [comment]
I am doing the final testing for naabu, with v2 and @payloadartist PR, everything should be working perfectly fine in some time.

**Comment by yogeshojha** [comment]
The problem was naabu had earlier -ports top-100, 80, 8080 syntax which is now changed to

-p 80, 8080
and 
-top-ports 100

So it failed.

**Comment by yogeshojha** [comment]
Now it has been fixed. 

https://github.com/yogeshojha/rengine/pull/346/files

Let me confirm if everything is working. Then I will merge. So far, going good.

**Comment by yogeshojha** [comment]
Thank you for reporting this. This has now been fixed. Build is passed 🚀 Happy reconnaissance

**Comment by h4ckerJi** [comment]
Hello team, 
when i install renginre i'm facing some installtion porblem 
can you check it out and give me a proper solution. 


[
![Screenshot 2023-01-31 123143](https://user-images.githubusercontent.com/86333136/215689764-619b24ee-ebca-41a6-91f7-083c2660ca48.png)
![Screenshot 2023-01-31 123021](https://user-images.githubusercontent.com/86333136/215689786-2f394aa8-dbe3-4e45-bed2-5ecc3b8903ca.png)
![Screenshot 2023-01-31 122946](https://user-images.githubusercontent.com/86333136/215689794-1c33c2f1-5d64-4aba-b21f-96eb4ef38835.png)
](url)

**Comment by ludbaziza** [comment]
Hello can some one helpme, when i installing rengine docker-compose -f docker-compose.dev.yml up, its take too long, i think i have spent 12 hours and still not yet finished. here is i sent the picture
![WhatsApp Image 2023-08-28 at 16 48 31](https://github.com/yogeshojha/rengine/assets/100133942/7f3d5c03-0132-4e97-b50a-f8b4a3975b91)

**Comment by AnonymousWP** [comment]
> Hello can some one helpme, when i installing rengine docker-compose -f docker-compose.dev.yml up, its take too long, i think i have spent 12 hours and still not yet finished. here is i sent the picture
> ![WhatsApp Image 2023-08-28 at 16 48 31](https://github.com/yogeshojha/rengine/assets/100133942/7f3d5c03-0132-4e97-b50a-f8b4a3975b91)
> 

Try using my fork.

**Comment by ludbaziza** [comment]
> > Hello can some one helpme, when i installing rengine docker-compose -f docker-compose.dev.yml up, its take too long, i think i have spent 12 hours and still not yet finished. here is i sent the picture
> > ![WhatsApp Image 2023-08-28 at 16 48 31](https://user-images.githubusercontent.com/100133942/263667089-7f3d5c03-0132-4e97-b50a-f8b4a3975b91.jpeg)
> 
> Try using my fork.

can you explain it in more detail, i dont understand
